server.port=8080

spring.application.name=tserver

spring.datasource.url=jdbc:postgresql://localhost:1000/postgres
spring.datasource.username=postgres
spring.datasource.password=pass01

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=3000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.leak-detection-threshold=2000

spring.flyway.enabled=true
spring.flyway.clean-disabled=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com

logging.level.root=INFO
